on:
  push:
    branches: ["main"]
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3
      
    - name: Install Dependencies
      run: npm ci
      
    - name: Build the app
      run: npm run build

    - name: Build the app
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        path: src
