on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1
      
    - name: Install Dependencies
      run: npm ci
      
    - name: Build the app
      run: npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        path: src
